development:
  adapter: postgresql
  database: woop
  host: localhost

test:
  adapter: postgresql
  database: woop
  host: localhost

production:
  adapter: postgresql
  database: woop
  host: localhost